### PR TITLE
Add ReadPasswordNoEcho

### PR DESCRIPTION
**Pull request by 178inaba**
This pull request provides input that does not display.

### CODE REVIEW

**Comment by mattn** [comment]
Thank you. NoMask seems have wrong meaning. How about NoEcho or NoFeedback or something instead?

**Comment by 178inaba** [comment]
Thank you for review!
I will use `NoEcho` that you suggested.

**Comment by 178inaba** [comment]
Done.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
