### PR TITLE
tinygo does not implement WriteString() for *os.File

### PR DESCRIPTION
**Pull request by srlehn**
Replace WriteString() calls on *os.File with Write() so that tinygo compiles.

### CODE REVIEW

**Comment by srlehn** [comment]
[(f *os.File) **WriteString**(s string)](https://pkg.go.dev/os/#File.WriteString) is only a call to Write() with the string cast to a []byte.

```go
func (f *File) WriteString(s string) (n int, err error) {
	return f.Write([]byte(s))
}
```

This commit does not change any behaviour.

**Comment by srlehn** [comment]
The error I got before changing the writes:

grafik

**Comment by mattn** [comment]
Thank you. Could you please make new global variable?

```
var linefeed = []byte{"\n"}
```

**Comment by srlehn** [comment]
done

**Comment by mattn** [comment]
Thank you

**Pull request merged**
