### PR TITLE
Fix: the unicode from U+2000 to U+2FFF could not be gotten

### PR DESCRIPTION
**Pull request by zetamatta**
I found some characters between U+2000 and U+2FFF which can not be gotten by ReadRune in Windows.
For example, `∞` and `Ⓓ`.

We can see the problem as below. (I did on Windows10)

1. Copy `∞Ⓓ` to the clipboard on the web browser.
2. `go run _example/readline.go`
3. Paste those characters from the clipboard by mouse-right-button.
4. We expect all of them are inserted, but we see no ones are inserted.

( See also https://github.com/zetamatta/nyagos/issues/390 . And https://github.com/judah/haskeline/issues/54 may be the similar problem )

I made [the test program](https://github.com/zetamatta/go-console-test) and saw the strange data from ReadConsoleInput.

1. On KeyDown event, the field UnicodeChar is zero. (Why!?)
2. On KeyUp event, th field UnicodeChar is valid as expected.
3. In some cases , trash data? may be inserted between two events.

I do not understand the reason that those input are given from ReadConsoleInput.
But, I want to fix the problem, so I made the patch for a workaround.
( A better solution may be exist, but I could not find it.) 

Would you merge this patch if problems do not exist , @mattn ?

### CODE REVIEW

**Comment by mattn** [comment]
Thank you. Please take me a little time to understand what this fixes.

**Comment by mattn** [comment]
Is this correctly on Linux?

**Comment by mattn** [comment]
Thank you

**Comment by zetamatta** [comment]
Thank you for merging.
When I know the reason for the behavior of ReadConsoleInput , I would report it or send a better code.

**Pull request merged**
